import { describe, expect, it } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { EMBEDDED_PLAYBOOKS, EMBEDDED_VERSION } from "../src/core/embeddedPlaybooks.js";

const playbooksDir = join(dirname(fileURLToPath(import.meta.url)), "..", "playbooks");

describe("embedded playbooks (generated by scripts/embedPlaybooks.mjs)", () => {
  it("matches every on-disk playbooks/*.md file byte-for-byte", () => {
    const files = readdirSync(playbooksDir).filter((f) => f.endsWith(".md"));
    expect(files.length).toBeGreaterThan(0);
    for (const file of files) {
      const phase = file.replace(/\.md$/, "");
      expect(EMBEDDED_PLAYBOOKS[phase]).toBe(readFileSync(join(playbooksDir, file), "utf8"));
    }
    // No stale entries left over from a renamed/removed playbook either.
    expect(Object.keys(EMBEDDED_PLAYBOOKS).sort()).toEqual(files.map((f) => f.replace(/\.md$/, "")).sort());
  });

  it("embeds a non-empty version string", () => {
    expect(typeof EMBEDDED_VERSION).toBe("string");
    expect(EMBEDDED_VERSION.length).toBeGreaterThan(0);
  });
});
