//! Skeleton for `src/core/embeddedPlaybooks.ts` - a GENERATED file (see its
//! header: "do not hand-edit"; regenerated by `scripts/embedPlaybooks.mjs`
//! from `playbooks/*.md` + `package.json`'s version). Wave 2 ports the
//! generation step itself (likely a `build.rs` or an equivalent script
//! producing this file's Rust counterpart) rather than hand-transcribing
//! the embedded literals here.
