//! Port of `src/core/embeddedPlaybooks.ts` - a GENERATED file in TS (see its
//! header: "do not hand-edit"; regenerated by `scripts/embedPlaybooks.mjs`
//! from `playbooks/*.md` + `package.json`'s version at `npm run build`
//! time, so a single-file binary has the playbooks compiled in with no
//! dependency on a `playbooks/` directory sitting next to it).
//!
//! Rust has no analogous "committed generated source" step: `include_str!`
//! embeds the same six files byte-for-byte at *compile* time, straight from
//! the repo's `playbooks/` directory (three `../` up from
//! `rust/src/core/` to the repo root) - byte-identical to the TS embed by
//! construction, with no generation script to keep in sync. This list is
//! exactly what `scripts/embedPlaybooks.mjs` embeds: every `playbooks/*.md`
//! file, sorted, keyed by filename minus `.md` (verified against
//! `readdirSync(playbooksDir).filter(f => f.endsWith(".md")).sort()`).

/// Playbook content by lowercase phase name, compiled in for single-file
/// binaries.
pub const EMBEDDED_PLAYBOOKS: &[(&str, &str)] = &[
    ("debug", include_str!("../../../playbooks/debug.md")),
    ("implement", include_str!("../../../playbooks/implement.md")),
    ("plan", include_str!("../../../playbooks/plan.md")),
    ("retro", include_str!("../../../playbooks/retro.md")),
    ("review", include_str!("../../../playbooks/review.md")),
    ("test", include_str!("../../../playbooks/test.md")),
];

/// The crate version this embed was built from (for `gate --version`).
/// TS's `EMBEDDED_VERSION` comes from `package.json` at generation time;
/// this crate's own version (`Cargo.toml`, kept in lockstep with
/// `package.json` per `docs/rust-port.md`) plays the same role via
/// `env!("CARGO_PKG_VERSION")` - no second hardcoded copy to drift.
pub const EMBEDDED_VERSION: &str = env!("CARGO_PKG_VERSION");

pub fn embedded_playbook(phase: &str) -> Option<&'static str> {
    EMBEDDED_PLAYBOOKS
        .iter()
        .find(|(name, _)| *name == phase)
        .map(|(_, content)| *content)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::Path;

    #[test]
    fn matches_every_on_disk_playbooks_md_file_byte_for_byte() {
        let playbooks_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../playbooks");
        let mut files: Vec<String> = fs::read_dir(&playbooks_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|f| f.ends_with(".md"))
            .collect();
        files.sort();
        assert!(!files.is_empty());

        let mut embedded_names: Vec<&str> = EMBEDDED_PLAYBOOKS.iter().map(|(n, _)| *n).collect();
        embedded_names.sort();
        let mut disk_names: Vec<String> = files
            .iter()
            .map(|f| f.trim_end_matches(".md").to_string())
            .collect();
        disk_names.sort();
        assert_eq!(embedded_names, disk_names);

        for file in &files {
            let phase = file.trim_end_matches(".md");
            let on_disk = fs::read_to_string(playbooks_dir.join(file)).unwrap();
            assert_eq!(embedded_playbook(phase).unwrap(), on_disk);
        }
    }

    #[test]
    fn embeds_a_non_empty_version_string() {
        assert!(!EMBEDDED_VERSION.is_empty());
    }
}
